/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Doğukan
 */
public class GUI_ManagerMenu_main_frm extends javax.swing.JFrame {

    /**
     * Creates new form mudur_main_frm
     */
    public GUI_ManagerMenu_main_frm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonManagerPanelBankSituation = new javax.swing.JButton();
        jButtonManagerPanelAddCostumer = new javax.swing.JButton();
        jButtonManagerPanelAddCurrency = new javax.swing.JButton();
        jButtonManagerPanelWorkersSalary = new javax.swing.JButton();
        jButtonManagerPanelOverdueInterest = new javax.swing.JButton();
        jButtonManagerPanelTransactions = new javax.swing.JButton();
        jButtonManagerPanelAdvanceSystem = new javax.swing.JButton();
        jLabelManagerPanelWelcome = new javax.swing.JLabel();
        jButtonManagerPanelExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButtonManagerPanelBankSituation.setBackground(new java.awt.Color(204, 255, 255));
        jButtonManagerPanelBankSituation.setText("Banka Durumu");
        jButtonManagerPanelBankSituation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagerPanelBankSituationActionPerformed(evt);
            }
        });

        jButtonManagerPanelAddCostumer.setBackground(new java.awt.Color(204, 255, 255));
        jButtonManagerPanelAddCostumer.setText("Müsteri Ekleme");
        jButtonManagerPanelAddCostumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagerPanelAddCostumerActionPerformed(evt);
            }
        });

        jButtonManagerPanelAddCurrency.setBackground(new java.awt.Color(204, 255, 255));
        jButtonManagerPanelAddCurrency.setText("Para Birimi Ekle");
        jButtonManagerPanelAddCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagerPanelAddCurrencyActionPerformed(evt);
            }
        });

        jButtonManagerPanelWorkersSalary.setBackground(new java.awt.Color(204, 255, 255));
        jButtonManagerPanelWorkersSalary.setText("Çalışanlarin Maaşı");
        jButtonManagerPanelWorkersSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagerPanelWorkersSalaryActionPerformed(evt);
            }
        });

        jButtonManagerPanelOverdueInterest.setBackground(new java.awt.Color(204, 255, 255));
        jButtonManagerPanelOverdueInterest.setText("Gecikme Faizi");
        jButtonManagerPanelOverdueInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagerPanelOverdueInterestActionPerformed(evt);
            }
        });

        jButtonManagerPanelTransactions.setBackground(new java.awt.Color(204, 255, 255));
        jButtonManagerPanelTransactions.setText("Gerceklesen Islemler");
        jButtonManagerPanelTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagerPanelTransactionsActionPerformed(evt);
            }
        });

        jButtonManagerPanelAdvanceSystem.setBackground(new java.awt.Color(204, 255, 255));
        jButtonManagerPanelAdvanceSystem.setText("Sistemi Ilerlet");
        jButtonManagerPanelAdvanceSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagerPanelAdvanceSystemActionPerformed(evt);
            }
        });

        jLabelManagerPanelWelcome.setBackground(new java.awt.Color(255, 255, 255));
        jLabelManagerPanelWelcome.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabelManagerPanelWelcome.setForeground(new java.awt.Color(0, 0, 255));
        jLabelManagerPanelWelcome.setText("Müdür Bey banka sistemine hosgeldiniz...");

        jButtonManagerPanelExit.setBackground(new java.awt.Color(153, 204, 255));
        jButtonManagerPanelExit.setText("Cikis");
        jButtonManagerPanelExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagerPanelExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelManagerPanelWelcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonManagerPanelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonManagerPanelAddCostumer, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jButtonManagerPanelBankSituation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonManagerPanelAddCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButtonManagerPanelWorkersSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonManagerPanelOverdueInterest, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonManagerPanelTransactions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonManagerPanelAdvanceSystem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelManagerPanelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonManagerPanelExit))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonManagerPanelBankSituation, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jButtonManagerPanelWorkersSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonManagerPanelAdvanceSystem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonManagerPanelTransactions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonManagerPanelAddCostumer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonManagerPanelOverdueInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonManagerPanelAddCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonManagerPanelWorkersSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManagerPanelWorkersSalaryActionPerformed
        GUI_ManagerMenu_WorkerSalary WorkerSalary = new GUI_ManagerMenu_WorkerSalary();
        WorkerSalary.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonManagerPanelWorkersSalaryActionPerformed

    private void jButtonManagerPanelOverdueInterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManagerPanelOverdueInterestActionPerformed
        GUI_ManagerMenu_OverdueInterest OverdueInterest = new GUI_ManagerMenu_OverdueInterest();
        OverdueInterest.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonManagerPanelOverdueInterestActionPerformed

    private void jButtonManagerPanelAddCostumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManagerPanelAddCostumerActionPerformed
        GUI_ManagerMenu_AddCustomer AddCustomer = new GUI_ManagerMenu_AddCustomer();
        AddCustomer.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonManagerPanelAddCostumerActionPerformed

    private void jButtonManagerPanelExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManagerPanelExitActionPerformed
        GUI_MainMenu_main_frm giris = new GUI_MainMenu_main_frm();
        giris.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonManagerPanelExitActionPerformed

    private void jButtonManagerPanelBankSituationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManagerPanelBankSituationActionPerformed
        GUI_ManagerMenu_BankSituation BankSituation = new GUI_ManagerMenu_BankSituation();
        BankSituation.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonManagerPanelBankSituationActionPerformed

    private void jButtonManagerPanelAddCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManagerPanelAddCurrencyActionPerformed
        GUI_ManagerMenu_AddCurrency AddCurrency = new GUI_ManagerMenu_AddCurrency();
        AddCurrency.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonManagerPanelAddCurrencyActionPerformed

    private void jButtonManagerPanelTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManagerPanelTransactionsActionPerformed
        GUI_ManagerMenu_Transactions Transactions = new GUI_ManagerMenu_Transactions();
        Transactions.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonManagerPanelTransactionsActionPerformed

    private void jButtonManagerPanelAdvanceSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManagerPanelAdvanceSystemActionPerformed
        GUI_ManagerMenu_AdvanceSystem AdvanceSystem = new GUI_ManagerMenu_AdvanceSystem();
        AdvanceSystem.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonManagerPanelAdvanceSystemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_ManagerMenu_main_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_ManagerMenu_main_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_ManagerMenu_main_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_ManagerMenu_main_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_ManagerMenu_main_frm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonManagerPanelAddCostumer;
    private javax.swing.JButton jButtonManagerPanelAddCurrency;
    private javax.swing.JButton jButtonManagerPanelAdvanceSystem;
    private javax.swing.JButton jButtonManagerPanelBankSituation;
    private javax.swing.JButton jButtonManagerPanelExit;
    private javax.swing.JButton jButtonManagerPanelOverdueInterest;
    private javax.swing.JButton jButtonManagerPanelTransactions;
    private javax.swing.JButton jButtonManagerPanelWorkersSalary;
    private javax.swing.JLabel jLabelManagerPanelWelcome;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
