/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Doğukan
 */
public class GUI_WorkerMenu_main_frm extends javax.swing.JFrame {

    /**
     * Creates new form worker_main_frm
     */
    public GUI_WorkerMenu_main_frm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCostumerPanelMoneyWithdrawDeposit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonWorkerPanelCostumerAddDeleteUpdate = new javax.swing.JButton();
        jButtonWorkerPanelCostumerGeneral = new javax.swing.JButton();
        jButtonWorkerPanelCostumerRequest = new javax.swing.JButton();
        jButtonWorkerPanelCostumerActions = new javax.swing.JButton();
        jLabelWorkerrPanelWelcome = new javax.swing.JLabel();
        jButtonWorkerPanelExit = new javax.swing.JButton();

        jButtonCostumerPanelMoneyWithdrawDeposit.setText("Para Cekme ve Yatirma");
        jButtonCostumerPanelMoneyWithdrawDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCostumerPanelMoneyWithdrawDepositActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 255));

        jButtonWorkerPanelCostumerAddDeleteUpdate.setBackground(new java.awt.Color(204, 255, 255));
        jButtonWorkerPanelCostumerAddDeleteUpdate.setText("Musteri Ekleme Silime ve Duzenleme");
        jButtonWorkerPanelCostumerAddDeleteUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWorkerPanelCostumerAddDeleteUpdateActionPerformed(evt);
            }
        });

        jButtonWorkerPanelCostumerGeneral.setBackground(new java.awt.Color(204, 255, 255));
        jButtonWorkerPanelCostumerGeneral.setText("Musterilerin Genel Durumlari");
        jButtonWorkerPanelCostumerGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWorkerPanelCostumerGeneralActionPerformed(evt);
            }
        });

        jButtonWorkerPanelCostumerRequest.setBackground(new java.awt.Color(204, 255, 255));
        jButtonWorkerPanelCostumerRequest.setText("Musterilerilerden Gelen Talepler");
        jButtonWorkerPanelCostumerRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWorkerPanelCostumerRequestActionPerformed(evt);
            }
        });

        jButtonWorkerPanelCostumerActions.setBackground(new java.awt.Color(204, 255, 255));
        jButtonWorkerPanelCostumerActions.setText("Musterilerilerin Islemleri");
        jButtonWorkerPanelCostumerActions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWorkerPanelCostumerActionsActionPerformed(evt);
            }
        });

        jLabelWorkerrPanelWelcome.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabelWorkerrPanelWelcome.setForeground(new java.awt.Color(0, 51, 255));
        jLabelWorkerrPanelWelcome.setText("Degerli Musteri Temsilcimiz banka sistemine hosgeldiniz...");

        jButtonWorkerPanelExit.setBackground(new java.awt.Color(153, 204, 255));
        jButtonWorkerPanelExit.setText("Cikis");
        jButtonWorkerPanelExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWorkerPanelExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelWorkerrPanelWelcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jButtonWorkerPanelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonWorkerPanelCostumerAddDeleteUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonWorkerPanelCostumerGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonWorkerPanelCostumerRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(jButtonWorkerPanelCostumerActions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWorkerrPanelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonWorkerPanelExit))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonWorkerPanelCostumerAddDeleteUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonWorkerPanelCostumerRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonWorkerPanelCostumerActions, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonWorkerPanelCostumerGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonWorkerPanelExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWorkerPanelExitActionPerformed
        GUI_MainMenu_main_frm giris = new GUI_MainMenu_main_frm();
        giris.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonWorkerPanelExitActionPerformed

    private void jButtonCostumerPanelMoneyWithdrawDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCostumerPanelMoneyWithdrawDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCostumerPanelMoneyWithdrawDepositActionPerformed

    private void jButtonWorkerPanelCostumerAddDeleteUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWorkerPanelCostumerAddDeleteUpdateActionPerformed
       GUI_WorkerMenu_AddDeleteCustomer AddDeleteCustomer = new GUI_WorkerMenu_AddDeleteCustomer();
       AddDeleteCustomer.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButtonWorkerPanelCostumerAddDeleteUpdateActionPerformed

    private void jButtonWorkerPanelCostumerGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWorkerPanelCostumerGeneralActionPerformed
        GUI_WorkerMenu_CustomerGeneral General = new GUI_WorkerMenu_CustomerGeneral();
        General.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonWorkerPanelCostumerGeneralActionPerformed

    private void jButtonWorkerPanelCostumerRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWorkerPanelCostumerRequestActionPerformed
        GUI_WorkerMenu_CustomerRequest CustomerRequest = new GUI_WorkerMenu_CustomerRequest();
        CustomerRequest.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonWorkerPanelCostumerRequestActionPerformed

    private void jButtonWorkerPanelCostumerActionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWorkerPanelCostumerActionsActionPerformed
        GUI_WorkerMenu_CustomerActions CustomerActions = new GUI_WorkerMenu_CustomerActions();
        CustomerActions.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonWorkerPanelCostumerActionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_WorkerMenu_main_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_WorkerMenu_main_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_WorkerMenu_main_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_WorkerMenu_main_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_WorkerMenu_main_frm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCostumerPanelMoneyWithdrawDeposit;
    private javax.swing.JButton jButtonWorkerPanelCostumerActions;
    private javax.swing.JButton jButtonWorkerPanelCostumerAddDeleteUpdate;
    private javax.swing.JButton jButtonWorkerPanelCostumerGeneral;
    private javax.swing.JButton jButtonWorkerPanelCostumerRequest;
    private javax.swing.JButton jButtonWorkerPanelExit;
    private javax.swing.JLabel jLabelWorkerrPanelWelcome;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
