
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Doğukan
 */
public class GUI_CustomerMenu_MoneyWithdrawDeposit extends javax.swing.JFrame {
    musterilerManager tm = new musterilerManager();
    /**
     * Creates new form GUI_CustomerMenu_MoneyWithdrawDeposit
     */
    public GUI_CustomerMenu_MoneyWithdrawDeposit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCostumerPanelExit1 = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jPanelMoneyWithdraw = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMoneyWithdraw = new javax.swing.JLabel();
        jButtonMoneyWithdraw = new javax.swing.JButton();
        jTextFieldWithdrawInputAmount = new javax.swing.JTextField();
        jPanelMoneyDeposit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMoneyDeposit = new javax.swing.JLabel();
        jButtonMoneyDeposit = new javax.swing.JButton();
        jTextFieldDepositInputAmount1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCostumerPanelExit1.setBackground(new java.awt.Color(255, 0, 0));
        jButtonCostumerPanelExit1.setText("Cikis");
        jButtonCostumerPanelExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCostumerPanelExit1ActionPerformed(evt);
            }
        });

        jButtonBack.setBackground(new java.awt.Color(51, 51, 255));
        jButtonBack.setText("Geri");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanelMoneyWithdraw.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setText("PARA ÇEKME");

        jLabelMoneyWithdraw.setText("Lutfen para cekmek istediginiz miktrari giriniz.");

        jButtonMoneyWithdraw.setBackground(new java.awt.Color(51, 153, 0));
        jButtonMoneyWithdraw.setText("PARA ÇEK");
        jButtonMoneyWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoneyWithdrawActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMoneyWithdrawLayout = new javax.swing.GroupLayout(jPanelMoneyWithdraw);
        jPanelMoneyWithdraw.setLayout(jPanelMoneyWithdrawLayout);
        jPanelMoneyWithdrawLayout.setHorizontalGroup(
            jPanelMoneyWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMoneyWithdrawLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelMoneyWithdrawLayout.createSequentialGroup()
                .addGroup(jPanelMoneyWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMoneyWithdrawLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabelMoneyWithdraw))
                    .addGroup(jPanelMoneyWithdrawLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(jPanelMoneyWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonMoneyWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jTextFieldWithdrawInputAmount))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanelMoneyWithdrawLayout.setVerticalGroup(
            jPanelMoneyWithdrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMoneyWithdrawLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMoneyWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldWithdrawInputAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMoneyWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelMoneyDeposit.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("PARA YATIRMA");

        jLabelMoneyDeposit.setText("Lutfen para yatirmak istediginiz miktrari giriniz.");

        jButtonMoneyDeposit.setBackground(new java.awt.Color(255, 0, 51));
        jButtonMoneyDeposit.setText("PARA YATIR");
        jButtonMoneyDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoneyDepositActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMoneyDepositLayout = new javax.swing.GroupLayout(jPanelMoneyDeposit);
        jPanelMoneyDeposit.setLayout(jPanelMoneyDepositLayout);
        jPanelMoneyDepositLayout.setHorizontalGroup(
            jPanelMoneyDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMoneyDepositLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMoneyDepositLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMoneyDeposit)
                .addGap(92, 92, 92))
            .addGroup(jPanelMoneyDepositLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanelMoneyDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldDepositInputAmount1)
                    .addComponent(jButtonMoneyDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanelMoneyDepositLayout.setVerticalGroup(
            jPanelMoneyDepositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMoneyDepositLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMoneyDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jTextFieldDepositInputAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMoneyDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 143, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelMoneyWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jPanelMoneyDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCostumerPanelExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBack)
                    .addComponent(jButtonCostumerPanelExit1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelMoneyWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMoneyDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCostumerPanelExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCostumerPanelExit1ActionPerformed
        GUI_MainMenu_main_frm giris = new GUI_MainMenu_main_frm();
        giris.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCostumerPanelExit1ActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        GUI_CostumerMenu_main_frm CustomerMain = new GUI_CostumerMenu_main_frm();
        CustomerMain.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonMoneyWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoneyWithdrawActionPerformed
        tm.paracek(Integer.parseInt(jTextFieldWithdrawInputAmount.getText()), Long.parseLong(GUI_MainMenu_main_frm.TC));
        jTextFieldWithdrawInputAmount.setText("");
    }//GEN-LAST:event_jButtonMoneyWithdrawActionPerformed

    private void jButtonMoneyDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoneyDepositActionPerformed
        try {
            tm.parayatir(Integer.parseInt(jTextFieldDepositInputAmount1.getText()), Long.parseLong(GUI_MainMenu_main_frm.TC));
            jTextFieldDepositInputAmount1.setText("");
        } catch (SQLException ex) {
            System.out.println("Para yatirilamadi");
        }
    }//GEN-LAST:event_jButtonMoneyDepositActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_CustomerMenu_MoneyWithdrawDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_CustomerMenu_MoneyWithdrawDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_CustomerMenu_MoneyWithdrawDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_CustomerMenu_MoneyWithdrawDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_CustomerMenu_MoneyWithdrawDeposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCostumerPanelExit1;
    private javax.swing.JButton jButtonMoneyDeposit;
    private javax.swing.JButton jButtonMoneyWithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMoneyDeposit;
    private javax.swing.JLabel jLabelMoneyWithdraw;
    private javax.swing.JPanel jPanelMoneyDeposit;
    private javax.swing.JPanel jPanelMoneyWithdraw;
    private javax.swing.JTextField jTextFieldDepositInputAmount1;
    private javax.swing.JTextField jTextFieldWithdrawInputAmount;
    // End of variables declaration//GEN-END:variables
}
